# Generated by Django 3.0.5 on 2020-04-25 08:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='name', max_length=300)),
                ('description', models.TextField(default='')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.IntegerField(default=0)),
                ('time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('place', models.TextField(default='')),
                ('photo', models.CharField(default='', max_length=500)),
                ('category_id', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
