# Generated by Django 3.0.5 on 2020-04-26 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200426_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='title', max_length=300),
        ),
    ]
