# Generated by Django 3.0.5 on 2020-04-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20200426_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
