# Generated by Django 3.0.5 on 2020-04-25 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200425_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='faculty',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='user',
            name='year_of_study',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
